# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subchapter',
            old_name='completed_course',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='chapter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
