# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='church',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
    ]
