# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160925_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='not set', max_length=40, null=True),
        ),
    ]
