# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20161002_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
